{% set name = "glob2" %}
{% set version = "0.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4f554074f242f01b48a9537409cdbc5e31355a06b51950c95f93fc061c324149

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed . --verbose

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - glob2

about:
  home: https://github.com/miracle2k/python-glob2
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Version of the glob module that supports recursion via **, and can capture patterns.

extra:
  recipe-maintainers:
    - dfroger
