travis:
  secure:
    BINSTAR_TOKEN: HrvoWAYCbJn2EIbE3C1b1xeWY1cZMiuBxmqqZSRwF6Vi3ymgPIOC8dzEIf+SXlCBbHOF77HAgEqQLGIetKm04HMMY2WHWjG7l4iiwoJu37Onr/b6UgcKjVuKRbAuQEjhYt1qOhhApCmvew/WMTPbSu6hTeMNeRMcscbHh1+DLLeBVTFRqYgWMWKP8UTGe5H6TQPjcE/4c7KkmYYgquaCOwEi03fWn/AuOuCmip9GJ3P+kHvQClnV2DzzPZ52NLwq3ZD5rtoMkrgLsHKrfXtZaJ/+S/lbNM4fyNHiKPFhimCvzsbp7+uiyCFzmPi6a7xPXwIMWLUGwo58uTa4S5xxxA+k4eT5nmqr1E7YIKC7A7+M8gMrfQHr/CzIt4mIri3qQqoxh+zWUvsljqMBl8+OQP67xn9OSUXzzbWqHO1EB4ONKwD+6ed8mPPWSbPwGJTwXxzumZ9ketO1drNzD7jFzQchRttaNRzfD+xuqUtpa5JdQcy0oQfuu1sicUH8OHjWLl6KcNlchI/Y5pOLByh5C7YhmeO3v3ir/cfrYO6V1++EZhKlq+Hcy9TVXk5rd2yV5trji0UYolJdUpmmBt+aZ10nZvXv9mZpGceoshJbR/bopviM/BLjAUxhxbp2UyaoxGZXri1gHdTwJFimO/raE1ohMx6Xh70+tTDRsv3YmnU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
